# escape=`

FROM microsoft/dotnet

RUN apt-get update
RUN apt-get install net-tools
RUN mkdir /apiexpress
WORKDIR /apiexpress

COPY "./" "/apiexpress/"
RUN dotnet restore
RUN dotnet publish -c Release -o ../Release

WORKDIR /apiexpress/Release
ENTRYPOINT ["dotnet", "CloudAPI.Server.dll"]

# You can then build and run the Docker image:
# docker build -t apiexpress .
# docker run -it -p 5000:5000 --rm apiexpress
